apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
        - name: my-nodejs-container
          image: myapp 
          ports:
            - containerPort: 3000 # Assuming your Node.js app listens on port 3000

