apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 3000 # Port on which your service will be exposed
      targetPort: 3000 # Port on which your container listens
      nodePort: 31000 # NodePort for accessing your service from outside the cluster
  selector:
    app: my-nodejs-app-deployment

